name: Sync-GitHub-to-Gitee
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee
      uses: ./.
      with:
        src: github/openspug
        dst: gitee/openspug
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: org
